version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app

  php:
    build: ./
    environment:
      PHP_IDE_CONFIG: "serverName=writeaway"
    volumes:
      - ./:/app
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "writeaway"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: "root_password"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql